### PR TITLE
Delete local libs and replace with gradle implementations

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Use gradle for versionName and versionCode
- Delete generated files and jar files and use implementations
- Delete local commonsware and use implementations
- Put notes next to some libraries that they are extremely outdated and have much newer versions

### CODE REVIEW

**Comment by konklone** [comment]
Thank you! These generally look good, though I'll test them on my phone and emulators before merging. Did you test these changes on a device or emulator yourself?

**Comment by konklone** [comment]
> No, because I didn't think there was a need to. No actual code was changed, so I think everything should build perfectly fine.

That's usually how it goes, though the commonsware WakefulIntent stuff has been brittle and buggy in the past (and I still get stuck wakelock reports sometimes).

> (Also, you should really take some time to update those libraries lmao)

This is a free app maintained by one person in their spare time. :) Updates come in bursts!

**Comment by TacoTheDank** [comment]
> This is a free app maintained by one person in their spare time. :) Updates come in bursts!
Lol I get it. Honestly I'd do it myself if I had the proper knowledge.

**Comment by TacoTheDank** [comment]
> This is a free app maintained by one person in their spare time. :) Updates come in bursts!

Lol I get it. Honestly I'd do it myself if I had the proper knowledge.

**Comment by TacoTheDank** [comment]
@konklone Will this be merged? I'd like to see something done lol.

**Comment by konklone** [comment]
Thanks for the poke. I've been very heads-down the last couple months, as I'm actually joining Congress as a staffer (through a fellowship: https://www.techcongress.io/fellows/). I just wrapped up an important milestone, so I'll try to get this merged this weekend.

**Comment by TacoTheDank** [comment]
Sounds awesome!

**Pull request merged**
